import discord
from discord.ext import commands

bot = commands.Bot(command_prefix = "!", intents=discord.Intents.all()) 

@bot.event
async def on_ready():
    print("Welcome to the Pokemon Generator! Type '!battle' to encounter a wild Pokemon.")

import random

pokemon = [
        "BULBASAUR",
        "IVYSAUR",
        "VENUSAUR",
        "CHARMANDER",
        "CHARMELEON",
        "CHARIZARD",
        "SQUIRTLE",
        "WARTORTLE",
        "BLASTOISE",
        "CATERPIE",
        "METAPOD",
        "BUTTERFREE",
        "WEEDLE",
        "KAKUNA",
        "BEEDRILL",
        "PIDGEY",
        "PIDGEOTTO",
        "PIDGEOT",
        "RATTATA",
        "RATICATE",
        "SPEAROW",
        "FEAROW",
        "EKANS",
        "ARBOK",
        "PIKACHU",
        "RAICHU",
        "SANDSHREW",
        "SANDSLASH",
        "NIDORAN(F)"
        "NIDORINA",
        "NIDOQUEEN",
        "NIDORAN(M)",
        "NIDORNIO",
        "NIDOKING",
        "CLEFAIRY",
        "CLEFABLE",
        "VULPIX",
        "NINETALES",
        "JIGGLYPUFF",
        "WIGGLYTUFF",
        "ZUBAT",
        "GOLBAT",
        "ODDISH",
        "GLOOM",
        "VILEPLUME",
        "PARAS",
        "PARASECT",
        "VENONAT",
        "VENOMOTH",
        "DIGLETT",
        "DUGTRIO",
        "MEOWTH",
        "PERSIAN",
        "PSYDUCK",
        "GOLDUCK",
        "MANKEY",
        "PRIMEAPE",
        "GROWLITHE",
        "ARCANINE",
        "POLIWAG",
        "POLIWHIRL",
        "POLIWRATH",
        "ABRA",
        "KADABRA",
        "ALAKAZAM",
        "MACHOP",
        "MACHOKE",
        "MACHAMP",
        "BELLSPROUT",
        "WEEPINBELL",
        "VICTREEBEL",
        "TENTACOOL",
        "TENTACRUEL",
        "GEODUDE",
        "GRAVELER",
        "GOLEM",
        "PONYTA",
        "RAPIDASH",
        "SLOWPOKE",
        "SLOWBRO",
        "MAGNEMITE",
        "MAGNETON",
        "FARFETCH'D",
        "DODUO",
        "DODRIO",
        "SEEL",
        "DEWGONG",
        "GRIMER",
        "MUK",
        "SHELLDER",
        "CLOYSTER",
        "GASTLY",
        "HAUNTER",
        "GENGAR",
        "ONIX",
        "DROWZEE",
        "HYPNO",
        "KRABBY",
        "KINGLER",
        "VOLTORB",
        "ELECTRODE",
        "EXEGGCUTE",
        "EXEGGUTOR",
        "CUBONE",
        "MAROWAK",
        "HITMONLEE",
        "HITMONCHAN",
        "LICKITUNG",
        "KOFFING",
        "WEEZING",
        "RHYHORN",
        "RHYDON",
        "CHANSEY",
        "TANGELA",
        "KANGASKHAN",
        "HORSEA",
        "SEADRA",
        "GOLDEEN",
        "SEAKING",
        "STARYU",
        "STARMIE",
        "MR. MIME",
        "SCYTHER",
        "JYNX",
        "ELECTABUZZ",
        "MAGMAR",
        "PINSIR",
        "TAUROS",
        "MAGIKARP",
        "GYARADOS",
        "LAPRAS",
        "DITTO",
        "EEVEE",
        "VAPOREON",
        "JOLTEON",
        "FLAREON",
        "PROYGON",
        "OMANYTE",
        "OMASTAR",
        "KABUTO",
        "KABUTOPS",
        "AERODACTYL",
        "SNORLAX",
        "ARTICUNO",
        "ZAPDOS",
        "MOLTRES",
        "DRATINI",
        "DRAGONAIR",
        "DRAGONITE",
        "MEWTWO"
    ]


@bot.command()
async def battle(ctx):
    await ctx.send('A wild ' + random.choice(pokemon)  +  ' appeared!')
    
with open("token.txt") as f:
    token = f.read()

bot.run(token)